config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'

  get 'show' =>'pages#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
	:user
	end

	def resource
	@resource ||= User.new
	end

	def devise_mapping
	@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_app_header.html.erb
<nav class="navbar navbar-default navbar-app hidden-xs">
  <div class="container-fluid navbar-app-container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="nav-logo-wrapper">
        <a href="/">
          <img class="navbar-app-brand" src="http://i.imgur.com/tSslfxn.png" />
        </a>
      </div>
    </div>
    <form class="navbar-form navbar-left navbar-search" role="search">
      <div class="form-group">
        <input type="text" class="form-control navbar-search-input" placeholder="Where are you renting?">
      </div>
    </form>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('List Drone', new_user_registration_path, class: "btn btn-list-drone navbar-app-link list-drone") %></li>
        <li><%= link_to('Sign Up', new_user_registration_path, class: "navbar-app-link")  %></li>
        <li><%= link_to "Login", "#login", "data-toggle" => "modal", class: "navbar-app-link" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<nav class="navbar navbar-inverse navbar-app hidden-sm hidden-md hidden-lg">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="/">
        <img class="navbar-brand-mobile navbar-center-brand" src="http://i.imgur.com/2Tr8CKJ.png" />
      </a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_big_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="/">
        <img class="navbar-brand navbar-center-brand" src="http://i.imgur.com/2Tr8CKJ.png" />
      </a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Log in to Voyage</h4>
        <br />

        <button class="btn btn-facebook center-block"> <span class="cta-text">Log in with Facebook</span> </button>

        <p class="text-center small-spacer"><i>or</i></p>

        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

        		<div class="form-group">
							<%= f.email_field :email, :autofocus => true, class: "form-control", placeholder: "Email" %>
						</div>

        		<div class="form-group">
							<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
						</div>

						<%= link_to "Forgot your password?", new_password_path(resource_name), class: "forgot-password pull-right" %>

        		<div class="form-group no-margin">
							<%= f.submit "Sign in", :class => 'btn btn-block btn-small btn-success' %>
						</div>

					<div class="clearfix"></div>
				<% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_transparent_header.html.erb
<div class="transparent-header hidden-xs">
	<nav class="navbar">
	  <div class="transparent-container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a href="/">
	        <img class="navbar-brand transparent-logo" src="http://i.imgur.com/tSslfxn.png" />
	      </a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	      <ul class="nav navbar-nav navbar-right">
	      	<li><%= link_to('List Drone', show_path, class: "btn-white-outline") %></li>
	        <li><%= link_to('Sign Up', new_user_registration_path)  %></li>
	       	<li><%= link_to "Login", "#login", "data-toggle" => "modal" %></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
</div>


<nav class="navbar navbar-inverse navbar-app hidden-sm hidden-md hidden-lg">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed pull-left" onclick="$('body').toggleClass('slideout');">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
      <a href="/">
        <img class="navbar-brand-mobile navbar-center-brand" src="http://i.imgur.com/2Tr8CKJ.png" />
      </a>
    </div>
  </div><!-- /.container-fluid -->
</nav>
<nav class="nav--sm">
	<div class="nav-mask--sm" onclick="$('body').toggleClass('slideout');"></div>
	<!-- links -->
	<div class="nav-content--sm panel text-white">
		<div class="nav-header items-logged-in hidden">
			<div class="nav-profile clearfix">
				<div class="user-item pull-left">
					<a class="link-reset user-profile-link" href="/users/show/0">
						<div class="media-photo media-round user-profile-image">

						</div>
						User
					</a>
				</div>
			</div>
			<hr>
		</div>
		<div class="nav-menu-wrapper">
			<div class="va-container va-container-v va-container-h">
				<div class="va-middle nav-menu panel-body">
					<ul class="menu-group list-unstyled row-space-3">
						<li>
							<a href="/" class="link-reset menu-item" rel="nofollow">
								Home
							</a>
						</li>
						<li><%= link_to('List Drone', show_path, class: "btn-white-outline") %></li>
						<li><%= link_to('Sign Up', new_user_registration_path)  %></li>
						<li><%= link_to 'Modal Sign Up', new_user_registration_path, :'class' => 'register-modal' %></li>
						<li><%= link_to "Login", "#login", "data-toggle" => "modal" %></li>
					</ul>

				</div>
			</div>
		</div>
	</div>
	<!-- / links -->
</nav>

<!-- Modal -->
<div class="modal fade" id="sign_up_modal" tabindex="-1" role="dialog" aria-labelledby="sign_up_modal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Sign Up Voyage</h4>
			</div>
			<div class="modal-body">
				<iframe id="login_iframe">Loading...</iframe>
			</div>

		</div>
	</div>
</div>

<style>
	.nav--sm {
		position: fixed;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		z-index: 1049; /* default bootstrap modal is 1050 */
		visibility: hidden;
	}
	body.slideout .nav--sm {
		visibility: visible;
	}

	body.slideout .nav--sm .nav-mask--sm {
		opacity: .6;
		-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=60)";
	}

	 .nav-mask--sm {
		position: absolute;
		cursor: pointer;
		height: 100%;
		width: 100%;
		background-color: #000;
		opacity: 0;
		-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
		-webkit-transition: opacity 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		-moz-transition: opacity 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		-o-transition: opacity 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		transition: opacity 0.2s cubic-bezier(0.4, 0, 0.2, 1);
	}

	body.slideout .nav--sm .nav-content--sm {
		left: 0;
	}

	.panel {
		border: 1px solid #dce0e0;
		background-color: #fff;
		-webkit-border-radius: 0;
		-moz-border-radius: 0;
		border-radius: 0;
	}

	 .nav-content--sm {
		position: absolute;
		left: -285px;
		width: 285px;
		height: 100%;
		border: 0;
		background: #2b2d2d none;
		-webkit-transition: left 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		-moz-transition: left 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		-o-transition: left 0.2s cubic-bezier(0.4, 0, 0.2, 1);
		transition: left 0.2s cubic-bezier(0.4, 0, 0.2, 1);
	}

	 .nav-content--sm .nav-menu-wrapper {
		height: 100%;
		overflow-x: hidden;
		overflow-y: auto;
		-webkit-overflow-scrolling: touch;
	}

	.va-container-h {
		width: 100%;
	}
	.va-container-v {
		height: 100%;
	}
	.va-container {
		display: table;
		position: relative;
	}
	.list-unstyled {
		padding-left: 0;
		list-style: none;
	}

	.nav-content--sm .nav-menu .menu-group {
		margin-bottom: 34px;
		line-height: 46px;
	}

	#sign_up_modal {
		width: 100%;
		height: 100%;
		overflow-y: auto;
	}

	#sign_up_modal iframe {
		margin:0;
		border: none;
		width: 100%;
		height: auto;
		min-height: 100%;
		border-radius: 6px;
	}
		#sign_up_modal .modal-body, #sign_up_modal .modal-dialog, #sign_up_modal .modal-content {
			height: 100%;
		}
	#sign_up_modal .modal-body {
		margin-top:-59px;
		background: transparent;
		padding: 59px 0 0 !important;
	}
		#sign_up_modal button.close {
			position: relative;
			z-index: 1051; /* higher than modal box */
		}
		
		/*
		if you wanna modal fullscreen only on mobile, active the line bellow, and comment out the next line,
		if not, modals will full screen for all device on small screen */
	/*@media only screen and (max-device-width: 480px) {*/
		@media (max-width: 480px) {
		.modal-dialog {
			margin: 0 !important;
			padding: 0 !important;
		}
		.modal-dialog, .modal-content {
			width: 100vw;
			height: 100vh;
			min-height: 100vh;
		}
		.modal-content {
			border: none !important;
			box-shadow: none !important;
			border-radius: 0 !important;
		}

	}

</style>
<script>
	$('.register-modal').on('click', function(e){
		e.preventDefault();
		//console.log('Hello World');
		//$('#sign_up_modal').modal('show').find('.modal-body').load($(this).attr('href'));
		$('#sign_up_modal').modal('show').find('#login_iframe').attr("src", $(this).attr('href'));

		$('#login_iframe').load( function() {
			$('#login_iframe').contents().find("head")
					.append($("<style type='text/css'>  .navbar-inverse{display:none;}  </style>"));
		});

	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voyage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<%= render "layouts/login" %>

<% if content_for? :nav %>
  <%= content_for :nav %>
<% else %>
  <%= render 'layouts/app_header' %>
<% end %>



<%= notice %>
<%= alert %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<% content_for :nav, render('layouts/transparent_header') %>

<div class="landing">
  <div id="video" class="videoContainer hidden-xs">
    <video id="mainVideo" autoplay="true" loop="true" muted="true" poster="http://i.imgur.com/hInwwb7.jpg">
      <source src="https://cdn.streamable.com/video/mp4/081p.mp4" type="video/mp4">
    </video>
  </div>                                                                                          
  <div id="image" class="hidden-sm hidden-md hidden-lg videoContainer" style="min-width: 100%;">
    <img src="http://i.imgur.com/SuF4zQg.jpg?1" />  
  </div>
  <div class="landing-content page-container page-container-full text-center">
    <div class="landing-container landing-container-v landing-container-h">
      <div class="landing-middle">

        <h2 class="text-branding text-jumbo text-contrast space-1 hero__heading">
          It's Time to Fly
        </h2>
        <div class="h4 text-contrast space-4">
         Rent a drone from someone nearby.
        </div>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-4 hidden-xs">
          <div class="input-group">
            <input type="search" name="address" id="address" class="form-control landing-address" autofocus="autofocus" placeholder="Where do you want to rent?" required="required" autocomplete="off">
            <span class="input-group-btn">
              <button name="button" type="submit" value="search" class="btn btn-primary landing-address landing-button fa fa-search"></button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="input-group hidden-sm hidden-md hidden-lg">
        <input type="search" name="address" id="address" class="form-control mobile-landing-address gmaps-autocomplete" autofocus="autofocus" placeholder="Enter Your Delivery address" required="required" autocomplete="off">
        <span class="input-group-btn">
          <button name="button" type="submit" value="search" class="btn btn-primary mobile-landing-address landing-button fa fa-chevron-right"></button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="row space-top-8 visible-xs">
  <div class="rent-banner-mobile">
    <div class="rent-banner-background background-cover">
      <div class="va-container va-container-v va-container-h">
        <div class="va-middle rent-banner-content">
          <div class="rent-banner-title space-4">
            <strong>Rent out your drone today!</strong>
          </div>
          <div class="rent-banner-subtitle space-4">
            You can earn extra money by sharing your drone with people in your area.
          </div>
          <div class="col-xs-10 col-xs-offset-1">
            <a href="/" class="btn btn-primary btn-block btn-lowercase">See What You Can Earn</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 hidden-xs space-top-8">
  <div class="col-sm-6 col-md-8 no-padding">
    <div id="landingCarousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3200" data-pause="false">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide carousel-image" src="http://i.imgur.com/TNuYOsQ.jpg" alt="First slide">
        </div>
        <div class="item">
          <img class="second-slide carousel-image" src="http://i.imgur.com/Ru9LPcg.jpg" alt="Second slide">
        </div>
        <div class="item">
          <img class="third-slide carousel-image" src="http://i.imgur.com/Ru9LPcg.jpg" alt="Third slide">
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4 no-padding" style="background:#fff; height: 309.984px">
    <div class="va-container va-container-v va-container-h">
      <div class="va-middle rent-banner">
        <div class="rent-banner-title grey space-4 text-center">
          <strong>
            Rent out your drone today!
          </strong>
        </div>
        <div class="host-banner__subtitle grey space-4 text-center">
          You can earn extra money by sharing your drone with people in your area.
        </div>
        <div class="text-center">
          <a href="/" class="btn btn-primary btn-lowercase">See What You Can Earn</a>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="clearfix"></div>


<h2 class="text-center grey space-top-8 space-8">
  Drone Rentals in Atlanta, GA
</h2>

<div class="col-md-10 col-md-offset-1 drone-img">
  <a href="/" class="no-underline">
    <div class="col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-0 drone-img">
      <div class="drone-card" style="background-image: url('http://i.imgur.com/uvQdsmE.jpg?1')">
        <div class="va-container va-container-v va-container-h">
          <div class="va-middle text-center text-contrast">
            <div class="h2 medium-text no-margin text-shadow bring-front">
                DJI Inspire
            </div>
          </div>
        </div>
        <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
          <sup class="h6 text-contrast thin-text">
            $
          </sup>
          <span class="h3 price-amount thin-text">
            80
          </span>
        </div>
      </div>
    </div>
  </a>
  <div class="clearfix hidden-md hidden-lg"></div>
  <br class="visible-sm" />
  <br class="visible-sm" />
  <a href="/" class="no-underline">
    <div class="col-sm-6 col-md-4 drone-img">
      <div class="drone-card" style="background-image: url('http://i.imgur.com/EzDl3OO.jpg?1')">
        <div class="va-container va-container-v va-container-h">
          <div class="va-middle text-center text-contrast">
            <div class="h2 medium-text no-margin text-shadow">
                DJI Phantom
            </div>
          </div>
        </div>
        <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
          <sup class="h6 text-contrast thin-text">
            $
          </sup>
          <span class="h3 price-amount thin-text">
            60
          </span>
        </div>
      </div>
    </div>
  </a>
  <a href="/" class="no-underline">
    <div class="col-sm-6 col-md-4 drone-img">
      <div class="drone-card" style="background-image: url('http://i.imgur.com/iaTt1Xw.jpg?1')">
        <div class="va-container va-container-v va-container-h">
          <div class="va-middle text-center text-contrast">
            <div class="h2 medium-text no-margin text-shadow">
                3DR Solo
            </div>
          </div>
        </div>
        <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
          <sup class="h6 text-contrast thin-text">
            $
          </sup>
          <span class="h3 price-amount thin-text">
            60
          </span>
        </div>
      </div>
    </div>
  </a>


  <div class="clearfix"></div>

  <div class="col-sm-12 col-lg-4 col-lg-offset-4 hidden-xs space-top-8">
    <a href="" class="btn btn-default btn-lowercase btn-large btn-block">
      See All Drones
    </a>      
  </div>
</div>












<div class="clearfix"></div>
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />
<br /><br />

<div id="landingCarousel" class="carousel slide" data-ride="carousel" data-interval="3200" data-pause="false">
  <ol class="carousel-indicators">
    <li data-target="#landingCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#landingCarousel" data-slide-to="1" class=""></li>
    <li data-target="#landingCarousel" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="first-slide" src="http://i.imgur.com/xQiRF6e.jpg" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Example headline.</h1>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="second-slide" src="http://i.imgur.com/xQiRF6e.jpg" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Another example headline.</h1>
          <p><a class="btn btn-lg btn-white" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="third-slide" src="http://i.imgur.com/xQiRF6e.jpg" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>One more for good measure.</h1>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
</div>